version: '3'

services:
  users:
    build: ./users
    volumes:
      - ./users:/app
    expose:
      - 8080
    ports:
      - 8080:80
  rides:
    build: ./rides
    volumes:
      - ./rides:/app
    expose:
      - 8000
    ports:
      - 8000:80