version: '3'

services:
  users_service:
    image: users:latest
    build: ./users
    volumes:
      - ./users:/app
    expose:
      - 8080
    ports:
      - 8080:80
    container_name: users
    environment:
      - TEAM_NAME=CC_0072_0206_0262_0704
  rides_service:
    image: rides:latest
    build: ./rides
    volumes:
      - ./rides:/app
    expose:
      - 8000
    ports:
      - 8000:80
    container_name: rides
    environment:
      - TEAM_NAME=CC_0072_0206_0262_0704