version: '3'

services:
  rides:
    image: rides:latest
    build: ./rides
    volumes:
      - ./rides:/app
    expose:
      - 80
    ports:
      - 80:80
    container_name: rides
    environment:
      - TEAM_NAME=CC_0072_0206_0262_0704
      - ORCHHOST=ec2-35-153-161-27.compute-1.amazonaws.com
      - ORCHPORT=80
      - MYHOST=ec2-52-201-242-178.compute-1.amazonaws.com
      - MYPORT=80
      - BALANCER=rideshare-balancer-737325029.us-east-1.elb.amazonaws.com
